// GENERATED by tools/ps2/gen_soc_numbers.py from golden/phase0-v2/run1/DEMO_*/soc.tsv -- do not edit.
// 84 distinct get_number() expressions (1706 calls in 4 logs), sorted for strcmp binary search.

#include "soc_numbers.h"

typedef struct { const char *expr; fixed_t value; } socnumber_t;

static const socnumber_t soc_numbers[] = {
	{ "(TICRATE*13)/2", 227 },
	{ "0", 0 },
	{ "1", 1 },
	{ "100", 100 },
	{ "100*TICRATE", 3500 },
	{ "10000", 10000 },
	{ "105*TICRATE", 3675 },
	{ "110*TICRATE", 3850 },
	{ "120*TICRATE", 4200 },
	{ "135*TICRATE", 4725 },
	{ "150", 150 },
	{ "150*TICRATE", 5250 },
	{ "165*TICRATE", 5775 },
	{ "2", 2 },
	{ "20", 20 },
	{ "200", 200 },
	{ "210*TICRATE", 7350 },
	{ "240*TICRATE", 8400 },
	{ "250", 250 },
	{ "3", 3 },
	{ "30*TICRATE", 1050 },
	{ "300", 300 },
	{ "350", 350 },
	{ "4", 4 },
	{ "40*TICRATE", 1400 },
	{ "5*MUSICRATE", 5000 },
	{ "50", 50 },
	{ "50*TICRATE", 1750 },
	{ "500", 500 },
	{ "5000", 5000 },
	{ "60", 60 },
	{ "60*TICRATE", 2100 },
	{ "75*TICRATE", 2625 },
	{ "80*TICRATE", 2800 },
	{ "90*TICRATE", 3150 },
	{ "99", 99 },
	{ "CA2_GUNSLINGER", 2 },
	{ "CA2_MELEE", 3 },
	{ "CA_BOUNCE", 14 },
	{ "CA_FLOAT", 7 },
	{ "CA_FLY", 2 },
	{ "CA_GLIDEANDCLIMB", 3 },
	{ "CA_THOK", 1 },
	{ "CA_TWINSPIN", 15 },
	{ "DSS3K56", 393 },
	{ "GE_NIGHTSITEM|GE_NIGHTSPULL", 3 },
	{ "GE_NIGHTSPULL", 1 },
	{ "GRADE_A", 5 },
	{ "MT_CORK", 536 },
	{ "MT_LHRT", 537 },
	{ "MT_METALJETFUME", 5 },
	{ "MT_TAILSOVERLAY", 4 },
	{ "PRECIP_SNOW", 2 },
	{ "PRECIP_STORM", 1 },
	{ "PRECIP_STORM_NORAIN", 5 },
	{ "SFX_amwtr1", 47 },
	{ "SFX_amwtr2", 48 },
	{ "SFX_amwtr3", 49 },
	{ "SFX_amwtr4", 50 },
	{ "SFX_amwtr5", 51 },
	{ "SFX_amwtr6", 52 },
	{ "SFX_amwtr7", 53 },
	{ "SF_MACHINE|SF_DASHMODE|SF_MULTIABILITY", 19456 },
	{ "SF_NOJUMPSPIN|SF_NOJUMPDAMAGE|SF_FASTEDGE", 8576 },
	{ "SF_NOJUMPSPIN|SF_NOJUMPDAMAGE|SF_FASTWAIT", 4480 },
	{ "SF_SUPER", 1 },
	{ "SF_SUPER|SF_NOSUPERJUMPBOOST|SF_CANBUSTWALLS", 786433 },
	{ "SKINCOLOR_BLUE", 86 },
	{ "SKINCOLOR_BROWN", 17 },
	{ "SKINCOLOR_CYAN", 74 },
	{ "SKINCOLOR_GOLD", 48 },
	{ "SKINCOLOR_GREY", 4 },
	{ "SKINCOLOR_LAVENDER", 28 },
	{ "SKINCOLOR_ORANGE", 44 },
	{ "SKINCOLOR_PURPLE", 94 },
	{ "SKINCOLOR_RED", 33 },
	{ "SKINCOLOR_RUST", 45 },
	{ "SKINCOLOR_SHAMROCK", 62 },
	{ "SKINCOLOR_SKY", 77 },
	{ "SKINCOLOR_WHITE", 1 },
	{ "SKINCOLOR_YELLOW", 51 },
	{ "TICRATE*3", 105 },
	{ "TICRATE*4", 140 },
	{ "TICRATE/5", 7 },
};

#define NUMSOCNUMBERS (sizeof soc_numbers / sizeof soc_numbers[0])

// PS2 replacement of LUA_EvalMath: exact expression text -> value. false if unknown.
boolean PS2_SOCNumber(const char *word, fixed_t *value)
{
	size_t lo = 0, hi = NUMSOCNUMBERS;

	while (lo < hi)
	{
		size_t mid = lo + (hi - lo) / 2;
		int c = strcmp(word, soc_numbers[mid].expr);

		if (c == 0)
		{
			*value = soc_numbers[mid].value;
			return true;
		}
		if (c < 0)
			hi = mid;
		else
			lo = mid + 1;
	}
	return false;
}
