"""Generate src/ps2/soc_numbers.c from the PC reference get_number() log.

usage: gen_soc_numbers.py [--golden DIR] [--out FILE] [--check]
Reads DIR/DEMO_*/soc.tsv (header 'expression_hex<TAB>value'; one line per get_number call),
merges all demos (one expression must always give one value) and emits a table sorted by
strcmp() order (unsigned bytes) for binary search. --check: only verify, write nothing.
"""
import argparse
import glob
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
GOLDEN = ROOT / 'golden/phase0-v2/run1'
OUT = ROOT / 'src/ps2/soc_numbers.c'


def load(golden):
    table = {}  # expression bytes -> (value, first source)
    files = sorted(glob.glob(str(golden / 'DEMO_*/soc.tsv')))
    if not files:
        sys.exit('no soc.tsv under %s' % golden)
    calls = 0
    for f in files:
        lines = Path(f).read_bytes().decode('ascii').split('\n')
        if lines[0].rstrip('\r') != 'expression_hex\tvalue':
            sys.exit('%s: bad header' % f)
        for n, line in enumerate(lines[1:], 2):
            line = line.rstrip('\r')
            if not line:
                continue
            h, v = line.split('\t')
            key, val = bytes.fromhex(h), int(v)
            if not -2**31 <= val < 2**31:
                sys.exit('%s:%d: value out of INT32' % (f, n))
            if b'\0' in key:
                sys.exit('%s:%d: NUL in expression' % (f, n))
            calls += 1
            if key in table and table[key][0] != val:
                sys.exit('%s:%d: %r = %d, but %s says %d' % (f, n, key, val, table[key][1], table[key][0]))
            table.setdefault(key, (val, f))
    return table, calls, len(files)


def c_string(b):
    out = []
    for c in b:
        if c in (0x22, 0x5c):
            out.append(chr(92) + chr(c))
        elif 0x20 <= c < 0x7f and c != 0x3f:  # '?' escaped: no trigraphs
            out.append(chr(c))
        else:
            out.append(chr(92) + '%03o' % c)
    return '"' + ''.join(out) + '"'


def render(table, calls, nfiles, golden):
    rows = sorted(table.items())  # bytes order == strcmp order
    try:
        src = golden.relative_to(ROOT).as_posix()
    except ValueError:
        src = golden.as_posix()
    out = ['// GENERATED by tools/ps2/gen_soc_numbers.py from %s/DEMO_*/soc.tsv -- do not edit.' % src,
           '// %d distinct get_number() expressions (%d calls in %d logs), sorted for strcmp binary search.' % (len(rows), calls, nfiles),
           '',
           '#include "soc_numbers.h"',
           '',
           'typedef struct { const char *expr; fixed_t value; } socnumber_t;',
           '',
           'static const socnumber_t soc_numbers[] = {']
    for k, (v, _) in rows:
        out.append('\t{ %s, %d },' % (c_string(k), v))
    out += ['};',
            '',
            '#define NUMSOCNUMBERS (sizeof soc_numbers / sizeof soc_numbers[0])',
            '',
            '// PS2 replacement of LUA_EvalMath: exact expression text -> value. false if unknown.',
            'boolean PS2_SOCNumber(const char *word, fixed_t *value)',
            '{',
            '\tsize_t lo = 0, hi = NUMSOCNUMBERS;',
            '',
            '\twhile (lo < hi)',
            '\t{',
            '\t\tsize_t mid = lo + (hi - lo) / 2;',
            '\t\tint c = strcmp(word, soc_numbers[mid].expr);',
            '',
            '\t\tif (c == 0)',
            '\t\t{',
            '\t\t\t*value = soc_numbers[mid].value;',
            '\t\t\treturn true;',
            '\t\t}',
            '\t\tif (c < 0)',
            '\t\t\thi = mid;',
            '\t\telse',
            '\t\t\tlo = mid + 1;',
            '\t}',
            '\treturn false;',
            '}',
            '']
    return '\n'.join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--golden', type=Path, default=GOLDEN)
    ap.add_argument('--out', type=Path, default=OUT)
    ap.add_argument('--check', action='store_true')
    a = ap.parse_args()
    table, calls, nfiles = load(a.golden)
    text = render(table, calls, nfiles, a.golden)
    if a.check:
        cur = a.out.read_bytes().decode() if a.out.exists() else ''
        print('%d expressions, %d calls, %d logs; %s' % (len(table), calls, nfiles,
              'up to date' if cur == text else 'STALE'))
        sys.exit(0 if cur == text else 1)
    a.out.write_bytes(text.encode('ascii'))  # LF, like the other ps2 sources
    print('wrote %s: %d expressions (%d calls, %d logs)' % (a.out, len(table), calls, nfiles))


main()
